application: leetcoin-tactoe
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
 - deferred: on

handlers:
- url: /_ah/login_required
  script: openid/views/openid_handler.py
  
- url: /.*
  script: chatactoe.py
  login: required
  
libraries:
- name: webapp2
  version: "2.5.2"
